import { defineConfig } from "orval";

export default defineConfig({
  elepad: {
    input: "../../apps/api/openapi.json", // Reads a file generated by apps/api
    output: {
      target: "src/gen/client.ts",
      client: "react-query",
      httpClient: "fetch",
      prettier: true,
      override: {
        mutator: {
          path: "src/mutator.ts",
          name: "rnFetch",
        },
      },
    },
  },
});
