name: Historia de Usuario
description: Crea una nueva historia de usuario con criterios de aceptación
title: "[HISTORIA] "
labels: [""]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## 🎯 [Título]"

  - type: textarea
    id: historia
    attributes:
      label: Historia
      description: Como [rol] quiero [acción] para [beneficio]
      placeholder: Ej. Como usuario quiero crear un perfil para comenzar a usar Elepad
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## ✅ Criterios de Aceptación"

  - type: textarea
    id: criterios
    attributes:
      label: Criterios
      description: Lista de criterios de aceptación (checkboxes)
      placeholder: |
        - [ ] El sistema valida el formato del correo
        - [ ] El perfil se crea correctamente
    validations:
      required: true
