services:
  app:
    build:
      context: .. # repo root
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/elepad:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://elepad:elepad@db:5432/elepad
      EXPO_USE_DEV_SERVER: "1"
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_HOME: /opt/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    extra_hosts:
      - "host.docker.internal:host-gateway" # reach host-published ports from container
    ports:
      - "8081:8081" # React Native Metro
      - "8787:8787" # Hono API
      - "9000:19000" # Expo DevTools (UI)
      - "9001:19001" # Expo Debug (LAN)
      - "9002:19002" # Expo DevTools (WS)
