#!/usr/bin/env bash

# Run prettier on staged files
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown --list-different
# Update staged files to add changes made by prettier
git update-index --again
