import { useCallback, useSyncExternalStore } from "react";

/**
 * Represents an album that is currently being generated by the AI.
 */
export interface PendingAlbum {
  /** Temporary client-side ID */
  id: string;
  /** Album title provided by the user */
  title: string;
  /** URL of the first selected memory image, used as cover preview */
  coverPreviewUrl: string | null;
  /** Timestamp when creation was requested */
  createdAt: number;
}

// ── Module-level store ──────────────────────────────────────────────
let pendingAlbums: PendingAlbum[] = [];
const listeners = new Set<() => void>();

function emitChange() {
  for (const listener of listeners) listener();
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function getSnapshot(): PendingAlbum[] {
  return pendingAlbums;
}

// ── Public actions ──────────────────────────────────────────────────

/** Add a new pending album (called right after requesting creation). */
export function addPendingAlbum(album: Omit<PendingAlbum, "id" | "createdAt">) {
  const entry: PendingAlbum = {
    ...album,
    id: `pending-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    createdAt: Date.now(),
  };
  pendingAlbums = [entry, ...pendingAlbums];
  emitChange();
}

/** Remove a pending album by its temporary id. */
export function removePendingAlbum(id: string) {
  pendingAlbums = pendingAlbums.filter((a) => a.id !== id);
  emitChange();
}

/** Remove a pending album by its title (used when the real album appears). */
export function removePendingAlbumByTitle(title: string) {
  const normalised = title.trim().toLowerCase();
  pendingAlbums = pendingAlbums.filter(
    (a) => a.title.trim().toLowerCase() !== normalised,
  );
  emitChange();
}

/** Clear all pending albums (e.g. on logout). */
export function clearPendingAlbums() {
  pendingAlbums = [];
  emitChange();
}

// ── React hook ──────────────────────────────────────────────────────

/**
 * Subscribe to the global list of pending (in-creation) albums.
 * Returns the current list and helpers to mutate it.
 */
export function usePendingAlbums() {
  const albums = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  const add = useCallback(
    (album: Omit<PendingAlbum, "id" | "createdAt">) => addPendingAlbum(album),
    [],
  );

  const removeByTitle = useCallback(
    (title: string) => removePendingAlbumByTitle(title),
    [],
  );

  return { pendingAlbums: albums, addPendingAlbum: add, removePendingAlbumByTitle: removeByTitle };
}
