import { build } from "esbuild";

// This scripts bundles the Hono API for the Cloudflare Workers environment.

const outfile = "cloudflare-worker.js";

await build({
  entryPoints: ["src/app.ts"],
  outfile,
  bundle: true,
  format: "esm",
  platform: "neutral", // not Nodejs
  // These packages are ESM-only and use bare specifiers, or have Node.js dependencies, so we need to mark them as external.
  external: [
    "@react-pdf/renderer",
    "@supabase/supabase-js",
    "@hono/zod-openapi",
    "googleapis",
    "@google/generative-ai",
    "dotenv",
    "fs",
    "os",
    "path",
    "crypto",
    "puppeteer",
    "puppeteer-core",
    "@puppeteer/browsers",
    "node:os",
    "node:path",
    "node:fs",
    "node:child_process",
    "node:events",
    "node:stream",
    "node:http",
    "node:https",
    "node:url",
    "node:process",
    "node:readline",
    "node:assert",
    "node:fs/promises",
    "node:child_process",
    "node:stream",
    "node:util",
    "events",
    "http",
    "https",
    "net",
    "tls",
    "stream",
    "url",
    "zlib",
    "debug",
    "cosmiconfig",
    "once",
    "proxy-agent",
    "extract-zip",
    "yauzl",
    "fd-slicer",
    "pump",
    "end-of-stream",
    "util",
    "assert",
    "yargs",
    "y18n",
    "events-universal",
    "get-stream",
    "yargs-parser",
    "ws",
  ],
});

console.log(`✅ Bundled the API as a Cloudflare Worker at ${outfile}`);